/**
 * OpenClaw Config Generator
 *
 * Generates a complete, valid OpenClaw config.yaml from ClawHQ agent settings.
 * This is the bridge between the dashboard UI and the actual OpenClaw runtime.
 *
 * Supports all three deploy modes:
 *   - CLOUD:     Full config for Docker containers (bundled or BYOK keys)
 *   - LOCAL:     Partial config snippet for users to merge into their existing setup
 *   - DASHBOARD: Minimal config for the in-browser chat agent
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AgentSettings {
  agentId: string;
  agentName: string;
  modelProvider: string;
  model: string;
  deployMode: 'CLOUD' | 'LOCAL' | 'DASHBOARD';
  usesBundledApi: boolean;
  apiKey?: string | null;
  systemPrompt?: string | null;
  temperature: number;
  maxTokens: number;
  skills: string[];
  webhookToken?: string | null;
  channels: ChannelConfig[];
}

export interface ChannelConfig {
  type: string;          // TELEGRAM, DISCORD, WHATSAPP, SLACK, IMESSAGE, TEAMS
  config: Record<string, any>;
  isActive: boolean;
}

// ---------------------------------------------------------------------------
// Provider & Model Mapping
// ---------------------------------------------------------------------------

const PROVIDER_MAP: Record<string, string> = {
  claude:   'anthropic',
  openai:   'openai',
  gemini:   'google',
  deepseek: 'deepseek',
  grok:     'xai',
};

// Map dashboard model IDs to OpenClaw model strings
const MODEL_MAP: Record<string, string> = {
  // Anthropic
  'claude-sonnet-4-20250514':  'anthropic/claude-sonnet-4-20250514',
  'claude-opus-4-20250514':    'anthropic/claude-opus-4-20250514',
  'claude-haiku-4-20250514':   'anthropic/claude-haiku-4-20250514',
  // OpenAI
  'gpt-4o':                    'openai/gpt-4o',
  'gpt-4o-mini':               'openai/gpt-4o-mini',
  'gpt-4-turbo':               'openai/gpt-4-turbo',
  // Google
  'gemini-2.0-flash-exp':      'google/gemini-2.0-flash-exp',
  'gemini-1.5-pro':            'google/gemini-1.5-pro',
  'gemini-1.5-flash':          'google/gemini-1.5-flash',
  // DeepSeek
  'deepseek-chat':             'deepseek/deepseek-chat',
  'deepseek-reasoner':         'deepseek/deepseek-reasoner',
  // xAI
  'grok-2-1212':               'xai/grok-2-1212',
  'grok-2-vision-1212':        'xai/grok-2-vision-1212',
};

// Map skill IDs to OpenClaw tool policy entries
const SKILL_TO_TOOLS: Record<string, string[]> = {
  'web-search':   ['web_search'],
  'web-fetch':    ['web_fetch'],
  'code-exec':    ['exec', 'process'],
  'file-manager': ['read', 'write', 'edit'],
  'browser':      ['browser'],
  'cron':         ['cron'],
  'memory':       ['memory_search', 'memory_get'],
  'image-gen':    ['image'],
  'image-vision': ['image'],
  'tts':          ['tts'],
  'email':        ['exec'],       // email via exec/SMTP
  'calendar':     ['web_fetch'],  // calendar via API
  'database':     ['exec'],       // DB queries via exec
  'api-builder':  ['exec'],       // API creation via exec
  'github':       ['exec', 'web_fetch'],
  'notion':       ['web_fetch'],
  'slack-tools':  ['message'],
  'analytics':    ['web_fetch'],
  'pdf':          ['exec', 'read', 'write'],
  'scraper':      ['web_fetch', 'browser'],
};

// ---------------------------------------------------------------------------
// YAML Helpers (no dependency needed for simple YAML)
// ---------------------------------------------------------------------------

function yamlString(value: string): string {
  // Use block scalar for multi-line, quoted for single-line with special chars
  if (value.includes('\n')) return value;
  if (/[:{}\[\],&*?|>!%@`"']/.test(value) || value.trim() !== value) {
    return JSON.stringify(value);
  }
  return value;
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text.split('\n').map(line => line.length > 0 ? pad + line : line).join('\n');
}

// ---------------------------------------------------------------------------
// Config Generator
// ---------------------------------------------------------------------------

export function generateOpenClawConfig(settings: AgentSettings): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ═══════════════════════════════════════════════════════════════`);
  lines.push(`# OpenClaw Configuration — Generated by ClawHQ`);
  lines.push(`# Agent: ${settings.agentName} (${settings.agentId})`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# ═══════════════════════════════════════════════════════════════`);
  lines.push('');

  // ── Model ──
  const modelString = MODEL_MAP[settings.model]
    || `${PROVIDER_MAP[settings.modelProvider] || settings.modelProvider}/${settings.model}`;
  lines.push(`# AI Model`);
  lines.push(`model: "${modelString}"`);
  lines.push('');

  // ── Temperature / Max Tokens (as model params) ──
  if (settings.temperature !== 0.7 || settings.maxTokens !== 4096) {
    lines.push(`# Model Parameters`);
    if (settings.temperature !== 0.7) {
      lines.push(`temperature: ${settings.temperature}`);
    }
    if (settings.maxTokens !== 4096) {
      lines.push(`maxTokens: ${settings.maxTokens}`);
    }
    lines.push('');
  }

  // ── Gateway Port ──
  if (settings.deployMode === 'CLOUD') {
    lines.push(`# Gateway`);
    lines.push(`port: 18789`);
    lines.push('');
  }

  // ── Soul / System Prompt ──
  const soulContent = settings.systemPrompt || 'You are a helpful AI assistant deployed via ClawHQ.';
  lines.push(`# Agent Personality (SOUL.md content)`);
  lines.push(`soul: |`);
  lines.push(indent(soulContent, 2));
  lines.push('');

  // ── Tools / Skills ──
  const enabledTools = resolveToolsFromSkills(settings.skills);
  lines.push(`# Tool Policy`);
  if (enabledTools.length === 0) {
    lines.push(`safety:`);
    lines.push(`  tool_policy: "deny"`);
  } else {
    lines.push(`safety:`);
    lines.push(`  tool_policy: "allowlist"`);
    lines.push(`  allowed_tools:`);
    for (const tool of enabledTools) {
      lines.push(`    - ${tool}`);
    }
  }
  if (settings.deployMode === 'CLOUD') {
    lines.push(`  elevated: false`);
  }
  lines.push('');

  // ── Heartbeat ──
  lines.push(`# Heartbeat`);
  lines.push(`heartbeat:`);
  lines.push(`  intervalMs: 300000`);
  lines.push('');

  // ── Channels ──
  if (settings.channels.length > 0) {
    lines.push(`# Channels`);
    for (const ch of settings.channels) {
      if (!ch.isActive) continue;
      const channelYaml = generateChannelConfig(ch);
      if (channelYaml) {
        lines.push(channelYaml);
        lines.push('');
      }
    }
  }

  // ── Webhook (for ClawHQ health reporting) ──
  if (settings.webhookToken && settings.deployMode === 'CLOUD') {
    lines.push(`# ClawHQ Integration`);
    lines.push(`hooks:`);
    lines.push(`  agent:`);
    lines.push(`    token: "${settings.webhookToken}"`);
    lines.push('');
  }

  // ── Relay (for LOCAL mode) ──
  if (settings.deployMode === 'LOCAL') {
    lines.push(`# ClawHQ Relay — connects your local agent to the ClawHQ dashboard`);
    lines.push(`# Paste this into your existing OpenClaw config.yaml`);
    lines.push(`clawhq:`);
    lines.push(`  enabled: true`);
    lines.push(`  agentId: "${settings.agentId}"`);
    if (settings.webhookToken) {
      lines.push(`  token: "${settings.webhookToken}"`);
    }
    lines.push(`  server: "wss://clawhq.dev/relay"`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate a minimal config snippet for LOCAL mode users to paste.
 */
export function generateLocalSnippet(settings: AgentSettings): string {
  const lines: string[] = [];
  lines.push(`# ── ClawHQ Connector ──`);
  lines.push(`# Add this to your OpenClaw config.yaml to connect to ClawHQ`);
  lines.push(`# Your local settings (model, soul, tools) take priority`);
  lines.push('');
  lines.push(`clawhq:`);
  lines.push(`  enabled: true`);
  lines.push(`  agentId: "${settings.agentId}"`);
  if (settings.webhookToken) {
    lines.push(`  token: "${settings.webhookToken}"`);
  }
  lines.push(`  server: "wss://clawhq.dev/relay"`);
  return lines.join('\n');
}

/**
 * Generate a Docker environment file for cloud deployments.
 */
export function generateDockerEnv(settings: AgentSettings, resolvedApiKey: string): string {
  const lines: string[] = [];
  lines.push(`# Docker environment for agent ${settings.agentName}`);
  lines.push(`CLAWHQ_USER_ID=\${USER_ID}`);
  lines.push(`CLAWHQ_AGENT_ID=${settings.agentId}`);
  lines.push(`CLAWHQ_AGENT_NAME=${settings.agentName}`);
  lines.push(`CLAWHQ_MODEL_PROVIDER=${settings.modelProvider}`);
  lines.push(`CLAWHQ_MODEL=${settings.model}`);
  lines.push(`CLAWHQ_API_KEY=${resolvedApiKey}`);
  if (settings.webhookToken) {
    lines.push(`CLAWHQ_WEBHOOK_TOKEN=${settings.webhookToken}`);
  }
  if (settings.systemPrompt) {
    // Truncate for env var; full prompt goes in mounted config
    lines.push(`CLAWHQ_SYSTEM_PROMPT=${settings.systemPrompt.slice(0, 500)}`);
  }
  lines.push(`CLAWHQ_TEMPERATURE=${settings.temperature}`);
  lines.push(`CLAWHQ_MAX_TOKENS=${settings.maxTokens}`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Channel Config Generation
// ---------------------------------------------------------------------------

function generateChannelConfig(channel: ChannelConfig): string | null {
  const cfg = channel.config || {};
  const type = channel.type.toLowerCase();

  switch (type) {
    case 'telegram': {
      const lines = [`telegram:`];
      if (cfg.botToken) lines.push(`  token: "${cfg.botToken}"`);
      if (cfg.allowedUsers) lines.push(`  allowedUsers: [${cfg.allowedUsers}]`);
      if (cfg.webhookUrl) lines.push(`  webhookUrl: "${cfg.webhookUrl}"`);
      return lines.length > 1 ? lines.join('\n') : null;
    }
    case 'discord': {
      const lines = [`discord:`];
      if (cfg.botToken) lines.push(`  token: "${cfg.botToken}"`);
      if (cfg.guildId) lines.push(`  guildId: "${cfg.guildId}"`);
      if (cfg.channelId) lines.push(`  channelId: "${cfg.channelId}"`);
      return lines.length > 1 ? lines.join('\n') : null;
    }
    case 'whatsapp': {
      const lines = [`whatsapp:`];
      if (cfg.phoneNumberId) lines.push(`  phoneNumberId: "${cfg.phoneNumberId}"`);
      if (cfg.accessToken) lines.push(`  accessToken: "${cfg.accessToken}"`);
      if (cfg.verifyToken) lines.push(`  verifyToken: "${cfg.verifyToken}"`);
      return lines.length > 1 ? lines.join('\n') : null;
    }
    case 'slack': {
      const lines = [`slack:`];
      if (cfg.botToken) lines.push(`  botToken: "${cfg.botToken}"`);
      if (cfg.appToken) lines.push(`  appToken: "${cfg.appToken}"`);
      if (cfg.signingSecret) lines.push(`  signingSecret: "${cfg.signingSecret}"`);
      return lines.length > 1 ? lines.join('\n') : null;
    }
    case 'imessage': {
      return `# iMessage — requires macOS host with Messages.app configured\nimessage:\n  enabled: true`;
    }
    case 'teams': {
      const lines = [`teams:`];
      if (cfg.appId) lines.push(`  appId: "${cfg.appId}"`);
      if (cfg.appPassword) lines.push(`  appPassword: "${cfg.appPassword}"`);
      return lines.length > 1 ? lines.join('\n') : null;
    }
    default:
      return `# ${type} channel — configure manually`;
  }
}

// ---------------------------------------------------------------------------
// Skill → Tool Resolution
// ---------------------------------------------------------------------------

function resolveToolsFromSkills(skills: string[]): string[] {
  const toolSet = new Set<string>();
  for (const skillId of skills) {
    const tools = SKILL_TO_TOOLS[skillId];
    if (tools) {
      tools.forEach(t => toolSet.add(t));
    }
  }
  // Sort for deterministic output
  return Array.from(toolSet).sort();
}

/**
 * Validate that a generated config is structurally sound.
 */
export function validateConfig(yaml: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!yaml.includes('model:')) {
    errors.push('Missing required field: model');
  }

  // Check for obvious YAML syntax issues
  const lines = yaml.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Tab characters break YAML
    if (line.includes('\t')) {
      errors.push(`Line ${i + 1}: Contains tab character (use spaces)`);
    }
  }

  return { valid: errors.length === 0, errors };
}

export default {
  generateOpenClawConfig,
  generateLocalSnippet,
  generateDockerEnv,
  validateConfig,
};
